# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-18 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('num', models.IntegerField(default=0)),
                ('chi', models.IntegerField(default=0)),
                ('mat', models.IntegerField(default=0)),
                ('eng', models.IntegerField(default=0)),
                ('phy', models.IntegerField(default=0)),
                ('che', models.IntegerField(default=0)),
                ('allscore', models.IntegerField(default=0)),
            ],
        ),
    ]
